devtools::install_github("TongZhou2017/itol.toolkit")
library(itol.toolkit)
library(data.table)
setwd("/phylo_tree")

tree_1 <- "abunt-tree.nwk"
hub_1 <- create_hub(tree_1)
data_file_1<- "abunt-metadata.txt"
data_1 <- data.table::fread(data_file_1)

# relabel by genus
unit_1 <- create_unit(data = data_1 %>% select(ID, Genus),
                      key = "itol_3al_1_labels",
                      type = "LABELS",
                      tree = tree_1)
write_unit(unit_1,paste0(getwd(),"/itol_3al_1_labels_Genus.txt"))
# tree_colors range by phylum 按照门填充颜色
unit_2 <- create_unit(data = data_1 %>% select(ID, Phylum),
                      key = "itol_3al_2_range",
                      type = "TREE_COLORS",
                      subtype = "range",
                      tree = tree_1)
write_unit(unit_2,paste0(getwd(),"/itol_3al_2_range_Phylum.txt"))
# color_strip by class 分组圆环
set.seed(123)
unit_3 <- create_unit(data = data_1 %>% select(ID, Class),
                      key = "itol_3al_3_strip",
                      type = "DATASET_COLORSTRIP",
                      color = "wesanderson",
                      tree = tree_1)
unit_3@common_themes$basic_theme$margin <- 50
write_unit(unit_3,paste0(getwd(),"/itol_3al_3_strip_Class.txt"))
# simple_bar by NS
unit_4 <- create_unit(data = data_1 %>% select(ID, NS),
                      key = "itol_3al_4_simplebar",
                      type = "DATASET_SIMPLEBAR",
                      tree = tree_1)
unit_4@specific_themes$basic_plot$size_max <- 100
write_unit(unit_4,paste0(getwd(),"/itol_3al_4_simplebar.txt"))
# simple_bar by OS
unit_5 <- create_unit(data = data_1 %>% select(ID, NS,OS),
                      key = "itol_3al_5_multibar",
                      type = "DATASET_MULTIBAR",
                      tree = tree_1)
unit_5@specific_themes$basic_plot$size_max <- 100
write_unit(unit_5,paste0(getwd(),"/itol_3al_5_multibar.txt"))
# simple_bar by OS
unit_6 <- create_unit(data = data_1 %>% select(ID, Dissimilarity),
                      key = "itol_3al_6_gradient",
                      type = "DATASET_GRADIENT",
                      tree = tree_1)
unit_6@specific_themes$heatmap$color$min <- "#0000ff"
unit_6@specific_themes$heatmap$color$max <- "#ff0000"
write_unit(unit_6,paste0(getwd(),"/itol_3al_6_gradient.txt"))
  
unit_7 <- create_unit(data = data_1 %>% select(ID, NS,OS), 
                       key = "itol_7_heatmap",
                       type = "DATASET_HEATMAP", 
                       tree = tree_1)
write_unit(unit_7,paste0(getwd(),"/itol_7_heatmap.txt"))
